### ISSUE TITLE
The extension crushed as Programming Grid has updated to a new version

### ISSUE THREAD

**Issue by leavelet** [Guyutongxue/VSC_ProgrammingGrid#2]
When I tried to use the extension, an error occurred which says “maximum redirect reached".
I think it may be caused by the recent update of Programming grid. How to solve it?

**Comment by guyutongxue** [comment]
This issue is known, and I am working on it. A major update will be published later this day. Thanks for your patience.

**Comment by guyutongxue** [comment]
A new version has just been released. Reopen VS Code to update.
